# Generated by Django 5.2.2 on 2025-06-05 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_verification_tries_reset',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_username_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_tries_count',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in a valid Iranian format.', regex='^(?:\\+98|0)(?:\\s?)9[0-9]{9}$')]),
        ),
    ]
