# Generated by Django 5.2.3 on 2025-08-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_plmn_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plmn2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
