# Generated by Django 5.2.3 on 2025-06-12 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMobileTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ping', 'ping'), ('sms', 'sms'), ('down', 'down'), ('web', 'web'), ('up', 'up'), ('dns', 'dns')], max_length=6)),
                ('timestamp', models.DateTimeField()),
                ('test_domain', models.CharField()),
                ('result', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
