# Generated by Django 5.2.3 on 2025-06-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermobiletests',
            name='test_domain',
            field=models.CharField(blank=True, null=True),
        ),
    ]
