# Generated by Django 5.2.3 on 2025-08-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_tests', '0002_alter_usermobiletests_test_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermobiletests',
            name='name',
            field=models.CharField(choices=[('ping', 'ping'), ('sms', 'sms'), ('download', 'download'), ('web', 'web'), ('up', 'up'), ('dns', 'dns')], max_length=10),
        ),
    ]
