# Generated by Django 5.2.3 on 2025-06-12 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('plmn_id', models.IntegerField()),
                ('lac', models.IntegerField(blank=True, null=True)),
                ('rac', models.IntegerField(blank=True, null=True)),
                ('tac', models.IntegerField()),
                ('cell_id', models.IntegerField()),
                ('band', models.CharField(max_length=10)),
                ('arfcn', models.IntegerField()),
                ('rsrp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rsrq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rssi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rscp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ec_no', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rx_lev', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('network_type', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Location Data',
                'verbose_name_plural': 'User Location Data',
            },
        ),
    ]
