# Generated by Django 5.2.3 on 2025-06-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocationdata',
            name='power',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userlocationdata',
            name='quality',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
