# Generated by Django 5.2.3 on 2025-06-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_facilities', '0002_userlocationdata_power_userlocationdata_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocationdata',
            name='arfcn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlocationdata',
            name='cell_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlocationdata',
            name='tac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlocationdata',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
