# Generated by Django 5.2.3 on 2025-06-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_facilities', '0004_alter_userlocationdata_band_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocationdata',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=25),
        ),
        migrations.AlterField(
            model_name='userlocationdata',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=25),
        ),
    ]
